from sqlalchemy.orm import Session

from .models import Job

DEMO_JOBS = [
    {
        "title": "Cloud DevOps Engineer",
        "company": "DemoTech France",
        "location": "Paris",
        "country": "France",
        "description": "Build and operate cloud-native services using AWS, Kubernetes, Docker and Terraform. Work with CI/CD and Linux.",
        "skills": ["AWS", "Kubernetes", "Docker", "Terraform", "Linux", "CI/CD"],
        "min_experience_years": 2,
        "remote": True,
        "employment_type": "Full-time",
        "salary_min": 45000,
        "salary_max": 65000,
        "currency": "EUR",
        "url": "https://example.com/jobs/cloud-devops-france",
        "source": "demo",
    },
    {
        "title": "Backend Python Engineer",
        "company": "DemoCloud Switzerland",
        "location": "Zurich",
        "country": "Switzerland",
        "description": "Develop Python REST APIs with FastAPI, PostgreSQL and Redis. Deploy services with Docker and Kubernetes.",
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "Kubernetes"],
        "min_experience_years": 1,
        "remote": True,
        "employment_type": "Full-time",
        "salary_min": 85000,
        "salary_max": 115000,
        "currency": "CHF",
        "url": "https://example.com/jobs/backend-python-switzerland",
        "source": "demo",
    },
    {
        "title": "Cloud Engineer",
        "company": "Demo Systems Germany",
        "location": "Berlin",
        "country": "Germany",
        "description": "Automate cloud infrastructure with AWS, Terraform and Ansible. Maintain Linux systems and Kubernetes clusters.",
        "skills": ["AWS", "Terraform", "Ansible", "Linux", "Kubernetes", "Docker"],
        "min_experience_years": 2,
        "remote": False,
        "employment_type": "Full-time",
        "salary_min": 60000,
        "salary_max": 80000,
        "currency": "EUR",
        "url": "https://example.com/jobs/cloud-engineer-germany",
        "source": "demo",
    },
    {
        "title": "Full Stack Developer",
        "company": "Demo AI Canada",
        "location": "Toronto",
        "country": "Canada",
        "description": "Build web applications with Python, FastAPI, React, PostgreSQL and Docker. Experience with AWS is valuable.",
        "skills": ["Python", "FastAPI", "React", "PostgreSQL", "Docker", "AWS"],
        "min_experience_years": 1,
        "remote": True,
        "employment_type": "Full-time",
        "salary_min": 70000,
        "salary_max": 100000,
        "currency": "CAD",
        "url": "https://example.com/jobs/full-stack-canada",
        "source": "demo",
    },
    {
        "title": "AWS DevSecOps Engineer",
        "company": "Demo Cloud UAE",
        "location": "Dubai",
        "country": "UAE",
        "description": "Build secure AWS infrastructure and CI/CD pipelines. Use Docker, Kubernetes, Terraform and security scanning.",
        "skills": ["AWS", "Docker", "Kubernetes", "Terraform", "GitHub Actions", "DevSecOps"],
        "min_experience_years": 2,
        "remote": True,
        "employment_type": "Full-time",
        "salary_min": 180000,
        "salary_max": 260000,
        "currency": "AED",
        "url": "https://example.com/jobs/aws-devsecops-uae",
        "source": "demo",
    },
    {
        "title": "Remote Backend Engineer",
        "company": "Demo Remote Labs",
        "location": "Remote",
        "country": "Remote",
        "description": "Create scalable backend services using Python, FastAPI, PostgreSQL, Redis and cloud technologies.",
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "Cloud"],
        "min_experience_years": 1,
        "remote": True,
        "employment_type": "Full-time",
        "salary_min": 50000,
        "salary_max": 90000,
        "currency": "EUR",
        "url": "https://example.com/jobs/remote-backend",
        "source": "demo",
    },
    {
        "title": "Cloud Full Stack Developer",
        "company": "Demo Tunisia Tech",
        "location": "Tunis",
        "country": "Tunisia",
        "description": "Develop full stack applications and deploy them on AWS using Docker and CI/CD.",
        "skills": ["Python", "JavaScript", "AWS", "Docker", "PostgreSQL", "Git"],
        "min_experience_years": 1,
        "remote": True,
        "employment_type": "Full-time",
        "salary_min": 25000,
        "salary_max": 45000,
        "currency": "TND",
        "url": "https://example.com/jobs/cloud-full-stack-tunisia",
        "source": "demo",
    },
]


def seed_jobs(db: Session):
    if db.query(Job).count() > 0:
        return
    for data in DEMO_JOBS:
        db.add(Job(**data))
    db.commit()
